# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
        minecraft_version=26.1.2
        loader_version=0.19.2
        loom_version=1.16.2

# Mod Properties
        mod_version = b1.1
        maven_group = dev.i726
        archives_base_name = rocky

# Dependencies
        fabric_api_version=0.152.1+26.1.2
