# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx512m
org.gradle.java.home=/home/icho/.jdks/zulu25.34.17-ca-jdk25.0.3-linux_x64

# Fabric Properties
        minecraft_version=26.1.2
        loader_version=0.19.2
        loom_version=1.16.2

# Mod Properties
        mod_version = b26.1.2
        maven_group = dev.i726
        archives_base_name = rocky

# Dependencies
        fabric_api_version=0.152.1+26.1.2
